### PR TITLE
feat: Adds Variant prop that reflects chackra-ui variants

### PR DESCRIPTION
**Pull request by picninim**
fix: Extra padding when flushed styled was applied

This feature allow users to use different appearances in the same project

### CODE REVIEW

**Comment by csandman** [comment]
This looks good! However, I think using `variant` instead of `appearanceVariant` would be better, just for simplicity's sake.  If you make that change I'll merge.  I'll probably tweak the documentation a bit before I publish it but you don't need to worry about that, I can handle it.

**Comment by picninim** [comment]
> This looks good! However, I think using `variant` instead of `appearanceVariant` would be better, just for simplicity's sake. If you make that change I'll merge. I'll probably tweak the documentation a bit before I publish it but you don't need to worry about that, I can handle it.

Done! :D I happy to help !

**Review by csandman — APPROVED** [review]

**Comment by csandman** [comment]
Ok I made the changes I needed in order to approve (mostly documentation and organization changes) and published them in [`v4.2.0`](https://github.com/csandman/chakra-react-select/releases/tag/v4.2.0)!  You can see the docs for you new feature here:

- https://github.com/csandman/chakra-react-select#variant--options-outline--filled--flushed--unstyled--default-outline

**Comment by csandman** [comment]
You can see a demo for the prop here: https://codesandbox.io/s/chakra-react-select-variant-5cf755?file=/example.js

**Pull request merged**
